[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tirocinio"
version = "0.1.0"
dependencies = [
    "torch",
    "timm",
    "torchattacks",
    "matplotlib",
    "streamlit",
    "pandas"
]